/**
 * Unpack-and-patch path for macOS variants where the in-place Mach-O patch
 * would grow the binary.
 *
 * Mach-O segment shifting + ad-hoc re-signing for grown binaries is non-trivial
 * (~200-300 LoC of LC_SEGMENT_64 / LC_SYMTAB / LC_DYLD_INFO_ONLY field math).
 * Instead, on macOS we extract the embedded JS modules from the pristine Bun
 * binary, strip Bun's CommonJS wrapper from the entry, apply theme + prompt
 * patches as plain string substitutions, install the four runtime deps that
 * Bun externalizes (`ws`, `node-fetch`, `undici`, `yaml`) into a sibling
 * node_modules, and switch the wrapper to invoke `node <entry>` instead of
 * the native binary.
 *
 * The pristine binary container itself is left untouched - macOS code-signing
 * never enters the picture because we no longer execute that file.
 */

import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

import type { TweakccConfig } from '../../brands/types.js';
import type { OverlayMap } from '../prompt-pack/types.js';
import { extractAll, parseBunBinary } from '../bun-extract.js';

import { patchUnpackedEntry, type PatchUnpackedResult } from './js-patch.js';

/**
 * The four packages that Anthropic's Bun bundler externalizes (verified
 * empirically against CC 2.1.119: every other bare require() in the entry is
 * a Node built-in). Pinned to current latest-major to track API compatibility
 * without taking patch updates surprise.
 */
const RUNTIME_DEPENDENCIES: Record<string, string> = {
  ws: '^8.18.0',
  'node-fetch': '^3.3.2',
  undici: '^7.0.0',
  yaml: '^2.6.0',
};

export class UnpackAndPatchError extends Error {
  constructor(
    public readonly stage: 'extract' | 'patch' | 'deps',
    message: string
  ) {
    super(`unpack-and-patch (${stage}): ${message}`);
    this.name = 'UnpackAndPatchError';
  }
}

export interface UnpackAndPatchInputs {
  /** Pristine binary path - the SHA256-verified cache copy, not the variant's. */
  pristineBinaryPath: string;
  /** Target directory for the extracted JS tree (`<variantDir>/unpacked`). */
  unpackedDir: string;
  config: TweakccConfig;
  overlays: OverlayMap | null;
}

export interface UnpackAndPatchResult {
  /** Absolute path of the patched entry module to feed into `node`. */
  entryPath: string;
  patch: PatchUnpackedResult;
}

/**
 * Wipe `unpackedDir` if it exists, extract the pristine binary's JS modules
 * into it, strip the Bun wrapper + apply theme + apply prompt overlays, write
 * a package.json + run `npm install` for the externalized deps. Returns the
 * patched entry path that the variant wrapper should hand to `node`.
 */
export const unpackAndPatch = ({
  pristineBinaryPath,
  unpackedDir,
  config,
  overlays,
}: UnpackAndPatchInputs): UnpackAndPatchResult => {
  // Always start from a clean tree so re-runs (update flow) get the same
  // output as a from-scratch create. js-patch's anchors are not idempotent
  // because applyTheme expects pristine upstream labels.
  if (fs.existsSync(unpackedDir)) {
    fs.rmSync(unpackedDir, { recursive: true, force: true });
  }
  fs.mkdirSync(unpackedDir, { recursive: true });

  let buf: Buffer;
  try {
    buf = fs.readFileSync(pristineBinaryPath);
  } catch (err) {
    throw new UnpackAndPatchError('extract', `read ${pristineBinaryPath}: ${(err as Error).message}`);
  }

  let info;
  try {
    info = parseBunBinary(buf);
  } catch (err) {
    throw new UnpackAndPatchError('extract', `parseBunBinary: ${(err as Error).message}`);
  }

  try {
    extractAll(buf, info, unpackedDir, { manifest: true });
  } catch (err) {
    throw new UnpackAndPatchError('extract', (err as Error).message);
  }

  let patch: PatchUnpackedResult;
  try {
    patch = patchUnpackedEntry({ unpackedDir, config, overlays });
  } catch (err) {
    throw new UnpackAndPatchError('patch', (err as Error).message);
  }

  writePackageJson(unpackedDir);
  runNpmInstall(unpackedDir);

  return { entryPath: patch.entryPath, patch };
};

const writePackageJson = (unpackedDir: string): void => {
  const pkg = {
    name: 'cc-mirror-unpacked',
    version: '0.0.0',
    private: true,
    description:
      'Auto-generated by cc-mirror to host runtime dependencies that Bun externalizes from the standalone CC binary. Do not edit by hand.',
    dependencies: RUNTIME_DEPENDENCIES,
  };
  fs.writeFileSync(path.join(unpackedDir, 'package.json'), `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');
};

const runNpmInstall = (unpackedDir: string): void => {
  const result = spawnSync('npm', ['install', '--silent', '--no-audit', '--no-fund'], {
    cwd: unpackedDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    encoding: 'utf8',
  });

  if (result.error) {
    throw new UnpackAndPatchError('deps', `npm install failed to launch: ${result.error.message}`);
  }
  if (result.status !== 0) {
    const stderr = (result.stderr ?? '').trim();
    const stdout = (result.stdout ?? '').trim();
    const detail = stderr || stdout || `exit ${result.status}`;
    throw new UnpackAndPatchError('deps', `npm install exit ${result.status}: ${detail}`);
  }
};
